// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttrmohazrlojxbdntonk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cm1vaGF6cmxvanhiZG50b25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0OTgzNzMsImV4cCI6MjA0OTA3NDM3M30.PLxd1mUoDb4Hhj6NVhasWHdXHljqsJ_khlEcNAl_LpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);